<a href="https://colab.research.google.com/github/ThuaNguyen0803/ML_Zoomcamp_2026_Homework/blob/main/Homework_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [39]:
import pandas as pd

#**Q1. Pandas version**

In [40]:
pd.__version__

'2.2.3'

**Getting the data**

In [41]:
!wget https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv

--2026-09-28 21:03:53--  https://raw.githubusercontent.com/DataTalksClub/machine-learning-zoomcamp/main/cohorts/2026/data/car_fuel_efficiency_2026.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 635180 (620K) [text/plain]
Saving to: ‘car_fuel_efficiency_2026.csv.2’

car_fuel_efficiency 100%[===================>] 620.29K  3.98MB/s    in 0.2s

2026-09-28 21:03:54 (3.98 MB/s) - ‘car_fuel_efficiency_2026.csv.2’ saved [635180/635180]

I had to add ! before wget so Colab knows to execute it as a shell command. Wget was being interpreted as Python code but it's a shell command.

#**Q2. Records count**

In [42]:
df = pd.read_csv('car_fuel_efficiency_2026.csv')
print(f'Number of records: {len(df)}')

# Or I can using shape
print(f'Rows, Columns: {df.shape}')

Number of records: 10000
Rows, Columns: (10000, 11)

In [43]:
# Display the first 20 rows of the dataset
display(df.head(20))

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0
5,2007,USA,Hybrid,Front-wheel drive,2,2290,6,266.0,4260,18.8,31.2
6,1992,Asia,Gasoline,Front-wheel drive,2,2270,6,250.0,4310,21.7,26.8
7,2005,USA,Gasoline,Front-wheel drive,4,2370,6,279.0,4090,17.4,30.2
8,1997,Asia,Gasoline,Rear-wheel drive,3,2330,6,251.0,4230,19.5,30.9
9,2004,USA,Diesel,All-wheel drive,5,2330,6,280.0,4620,17.7,31.2
10,1978,Asia,Gasoline,All-wheel drive,3,2410,6,NaN,4420,19.5,26.8
11,1996,Europe,Diesel,Front-wheel drive,4,2240,6,250.0,3980,16.7,31.4
12,1983,USA,Diesel,Front-wheel drive,3,2370,7,NaN,4390,20.7,30.4
13,2024,USA,Gasoline,Rear-wheel drive,4,2440,6,277.0,4790,20.2,30.2
14,2015,USA,Gasoline,Front-wheel drive,5,1900,6,202.0,4070,18.7,32.8
15,2007,Asia,Diesel,Front-wheel drive,4,2170,5,226.0,3950,18.0,35.4
16,2021,Asia,Gasoline,All-wheel drive,5,2280,6,234.0,4750,20.1,29.7
17,2021,USA,Gasoline,Rear-wheel drive,5,2540,7,299.0,4690,17.9,30.2
18,1995,USA,Gasoline,Front-wheel drive,2,2490,6,264.0,4230,17.7,28.5
19,2006,USA,Gasoline,All-wheel drive,4,2320,6,251.0,4410,15.8,31.4

#**Q3. Fuel types**

In [44]:
#Check unique fuel types will simply tell how many fuel types presented in the dataset

#Show all unique fuel types
different_fuels = df['fuel_type'].unique()
print("Different unique fuel types:", different_fuels)

#Count how many unique fuel types there are
num_different_fuels = df['fuel_type'].nunique()
print("Number of different fuel types:", num_different_fuels)

# I can also see the distribution of each fuel type
display(df['fuel_type'].value_counts())

Different unique fuel types: ['Gasoline' 'Diesel' 'Hybrid']
Number of different fuel types: 3

fuel_type
Gasoline    6913
Diesel      2053
Hybrid      1034
Name: count, dtype: int64

3 functions I learned: unique(), nunique(), value_counts()

#**Q4. Missing values**

In [45]:
#Check how many missing values are in each column
missing_per_column = df.isnull().sum()
print("Missing values per column:")
print(missing_per_column)

# Check how many columns have at least one missing value
columns_with_missing = missing_per_column[missing_per_column > 0]
num_columns_with_missing = len(columns_with_missing)

print(f"\nNumber of columns with missing values: {num_columns_with_missing}")
if num_columns_with_missing > 0:
    print("Columns with missing values:", list(columns_with_missing.index))

Missing values per column:
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

Number of columns with missing values: 2
Columns with missing values: ['horsepower', 'acceleration']

#**Q5. Max fuel efficiency**

In [46]:

asia_cars = df[df['origin'] == 'Asia']
max_asia_fuel_efficiency = asia_cars['fuel_efficiency_mpg'].max()
print(f"The maximum fuel efficiency of cars from Asia is: {max_asia_fuel_efficiency}")

The maximum fuel efficiency of cars from Asia is: 41.2

#**Q6. Median value of horsepower**

In [47]:
# I calculated the initial median value of the horsepower column
initial_median = df['horsepower'].median()
print(f"Initial median of horsepower: {initial_median}")

# Find the most frequent value (mode) of the horsepower column
# I used [0] to get the actual value from .mode()
most_frequent_horsepower = df['horsepower'].mode()[0]
print(f"Most frequent horsepower value: {most_frequent_horsepower}")

# Fill the missing values in 'horsepower' with the most frequent value
df['horsepower'] = df['horsepower'].fillna(most_frequent_horsepower)

# Calculate the median value of horsepower once again
new_median = df['horsepower'].median()
print(f"New median of horsepower (after filling missing values): {new_median}")

Initial median of horsepower: 254.0
Most frequent horsepower value: 252.0
New median of horsepower (after filling missing values): 252.0


#**Q7. Sum of weights**

In [48]:
import numpy as np

# Select all the cars from Asia
asia_cars = df[df['origin'] == 'Asia']

# Select only columns 'vehicle_weight' and 'model_year'
subset_df = asia_cars[['vehicle_weight', 'model_year']]

# Select the first 7 values
first7_df = subset_df.head(7)
display(first7_df)

# Get the underlying NumPy array (X)
X = first7_df.values
print(X)

# Compute matrixmatrix multiplication between transpose of X (X.T) and X

XTX = X.T @ X

print(XTX)

# Invert XTX
XTX_inv = np.linalg.inv(XTX)

print(XTX_inv)

    vehicle_weight  model_year
2             4240        1996
6             4310        1992
8             4230        1997
10            4420        1978
15            3950        2007
16            4750        2021
22            4450        2019

[[4240 1996]
 [4310 1992]
 [4230 1997]
 [4420 1978]
 [3950 2007]
 [4750 2021]
 [4450 2019]]
[[131950500  60750580]
 [ 60750580  28041424]]
[[ 2.96830537e-06 -6.43071025e-06]
 [-6.43071025e-06  1.39675281e-05]]

In [50]:
# Create an array y with the specified values
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# Multiply the inverse of XTX with the transpose of X, and then multiply by y
w = (XTX_inv @ X.T) @ y

print(w)

# The sum of all the elements of the result w

sum_w = w.sum()
print(f"Sum of all elements of w: {sum_w:}")

[0.13644777 0.2327492 ]
Sum of all elements of w: 0.36919696904925486